### ISSUE TITLE
error in figure 1.

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#15]
Recording this so I fix it next time around.

\plr{Whoops!  genotype of 1 in the second tree should be `G'!}

**Comment by ashander** [comment]
Also, to be consistent with listings later in the text (and indeed the way print(ts.dump_tables()) looks the order of `child` and `parent` cols in the Edges table should be swapped

**Comment by petrelharp** [comment]
They all agree now.
