### ISSUE TITLE
Review of forward time simulators needed

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#16]
We need a paragraph or two giving a quick overview of the relevant forwards time simulators. Probably this goes in the introduction? 

I guess we should discuss [edited]:

1. simupop
2. fwdpp
2. sfs_code
2. slim/slim2 
3. forwsim
4. ana-fits
5. Also include references to a couple of  simulation review papers.

Any others? We should mention forwsim and ana-fits because they also work from the basic insight that carrying forward lots of neutral mutations is inefficient.

**Comment by molpopgen** [comment]
Slim/slim2 have to be mentioned, as it is pretty widely used.  forwsim and ana-fits should be discussed, but both are basically dead projects.  I'm trying to compile the former now, and I'm having to make lots of edits to the files.

**Comment by ashander** [comment]
We have some of this in the intro https://github.com/petrelharp/ftprime_ms/blob/412087c11b4b5612a6fbe6dfa3f27aed89a33e1f/forwards_paper.tex#L123-L134 now

Perhaps some needs to be added to discussion, likely here https://github.com/petrelharp/ftprime_ms/blob/412087c11b4b5612a6fbe6dfa3f27aed89a33e1f/forwards_paper.tex#L1033-L1039

Yay or nay?

**Comment by molpopgen** [comment]
I'd say the other way around?  I don't think we should wait to review the current tools until the end of the paper.

**Comment by ashander** [comment]
I guess to my mind this range https://github.com/petrelharp/ftprime_ms/blob/412087c11b4b5612a6fbe6dfa3f27aed89a33e1f/forwards_paper.tex#L105-L134 discusses the current tools. Perhaps it needs more specific references to specific tools. Also probably the next paragraph where we talk about not tracking neutral stuff should 

>  mention forwsim and ana-fits because they also work from the basic insight that carrying forward lots of neutral mutations is inefficient

but other than that it seems ok? Maybe I'll do those two suggestions and we'll see what @petrelharp has to say on his next pass through early next week or so.

**Comment by jeromekelleher** [comment]
The motivation for moving the mentions for forwsim and anafits to the discussion was that they aren't really competitive. We should discuss the forward simulators that people actually use, and I think we do that. Discussing forwsim and anafits in the intro muddies the message I think; we *are* doing something very different to them, and are not just slightly tweaking something they've already done. Not that we should ignore them: we discuss them in the discussion.

**Comment by petrelharp** [comment]
I think we're good here.
