### ISSUE TITLE
Figure showing simplify performance

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#20]
Simplify is very efficient, and it would be nice to have some way to make this efficiency concrete for the reader. I can think of two ways to do this:

1. Show the average time required to simplify a forward simulation of 10N (neutral) generations, with N on the x-axis. We claim that time is linear in the number of edges, so we should be able to fit a quadratic to the result.
2. Show the average time required to simplify random subsets of 10, 100, 1000,... samples from a single very large tree sequence. If we depend only on the number of input edges then the time should be constant for the different subsets. (I don't think it is though...)

Any thoughts? I'm not saying we should definitely do this figure, just bringing it up as a possibility.

**Comment by molpopgen** [comment]
I could generate a script to do the first.  The caveat is that we cannot let N get too big, else the RAM lights on fire.

**Comment by petrelharp** [comment]
Good thought.  It'd be nice to check this.  I guess I don't think it's essential, but if you're motivated, then sure.

Thinking through the timing - I think output size will affect things, but not strongly - Imagine the output ts embedded within the input ts.  I think the time to simplify is (time to process input tree sequence) + (time to propagate segments up through the embedded output tree sequence).  In the case of a WF-produced ts, for the second part simplify has to do something every generation when moving segments up each branch.  In any case, there's at most a constant number of segments dealt with in each input node, so the second part should be O(size of input tree sequence + size of output tree sequence).  I could be wrong, but I don't see any interaction between (output ts size) and (input ts size).

**Comment by jeromekelleher** [comment]
> I could generate a script to do the first. The caveat is that we cannot let N get too big, else the RAM lights on fire.

That would be great, thanks for offering @molpopgen! I don't think there's any point in making N any bigger than say 10K. We just do (say) 10/100 replicates for each N to get a meaningful number and it should all work out fine. The whole thing shouldn't take more than an hour to run, or we're overdoing it.

I'm just slightly curious about the second part @petrelharp. I might have a quick play around and see if there's anything interesting to be seen. It'll only take 10 minutes to code up the script, and it's just to satisfy my curiosity really.

**Comment by petrelharp** [comment]
sounds good to me.

**Comment by jeromekelleher** [comment]
First steps for this over in #21.

Thinking about the other side of the plot (I'm imaging a two panel figure here), what we actually want is to demonstrate that we are linear in the number of input edges. So, doing lots of different Ns is going to obscure this, since we have a logarithmic dependency on the sample size.

Perhaps what we want instead is to make one MASSIVE (like, 100G) table of edges from one simulation (N = 10, say). We can then run simplify on increasingly large subsets of this (x axis) and plot the time required (y axis). We should see a perfect linear relationship if our assertion that we depend linearly on the number of input edges is true.

Any thoughts?

**Comment by petrelharp** [comment]
If I follow, maybe something like this (modified from what you say):
1. Run three WF simulations with N: 100, 500, 2500 (say) for 10,000 gens
2. At a grid of time points in the simulations (say, 500 evenly spaced time points),
run simplify, for each of five choices of n (the number of samples simplified to): 10, 50, 100, 500, 1000 (for each `n <= N`)

This would give us 3, 4, and 5 lines for each value of N.    We could put them on the same plot; perhaps divided by number of generations to remove the linear increase of number of input edges (if it works out that way), and see how n and N interact.

I think this should still let us see the linear dependency on number of edges?

**Comment by jeromekelleher** [comment]
I think it would be simpler to break it up into two plots: (a) showing dependency on #of input edges, and (b) showing dependency on size of subsample. Plot (b) is basically the figure in #21. Plot (a) is the figure I suggested above: generate one huge set of edges, and then run simplify on a linspace of subsets of this (e.g., [(0, 1M), (0, 2M), ..., (0, 10M)]). We should see an exact straight line, and also get a good sense of how long it takes to simplify a given set of edges (or, how many mega-edges per second we can process.)

I don't think we learn anything from running for different Ns, it would just crowd the plot IMO.

Using a different data set for the two different plots is bad in one way (the numbers aren't comparable), but it's a good way of emphasising the two different applications of simplify that we have (thinning out forward simulation results, and finding subsets of huge existing tree sequences).

**Comment by molpopgen** [comment]
> I don't think we learn anything from running for different Ns, it would just crowd the plot IMO.

For the figs in #17, the y-axis is depending on N, implying the number of edges depends on N. Or, are those figs not really comparable, for e.g. with Nr being different?

**Comment by jeromekelleher** [comment]
> For the figs in #17, the y-axis is depending on N, implying the number of edges depends on N. Or, are those figs not really comparable, for e.g. with Nr being different?

Which figs in #17 @molpopgen?

**Comment by molpopgen** [comment]
Oops, I meant #18.

**Comment by molpopgen** [comment]
These two, for example: https://github.com/petrelharp/ftprime_ms/pull/18#issuecomment-345057004.  Hope this shows up right--not easy to GitHub by phone.

**Comment by petrelharp** [comment]
Sure, sounds good.  I'll be curious to see it.

**Comment by jeromekelleher** [comment]
Ah, ok, thanks @molpopgen. The number of edges for T generations is O(TN), but that's not what we're interested in here. We want to show that simplify is linear in the number of input edges, so N doesn't really matter. So, we just generate some large number of edges K using some (arbitrary) value of N and plot the time it takes to simplify K/10, 2K/10, ..., K of these edges.

**Comment by jeromekelleher** [comment]
Partially done in #21, but need to update the figure A to show muliple N values.

**Comment by petrelharp** [comment]
done in #58
