### ISSUE TITLE
role of neutral mutations in forward sim

### ISSUE THREAD

**Issue by ashander** [petrelharp/ftprime_ms#3]
TBD: are we comparing between using msprime and not, or something else?

1. forward time sim of selected sites => into msprime + add neutral after
2. forward time sim of selected sites and neural sites
3. ??

todo

- [x] full neutral sims for Kevin's stuff
- [x] full neutral sims for simuPOP stuff

**Comment by molpopgen** [comment]
We want to do 1 and 2.  Version two is the "regular" sim that everyone's forward sim engine does (except for [anafits](https://github.com/aberer/AnA-FiTS), which is no longer maintained, fragile, etc.).  

The [benchmarking script](https://github.com/molpopgen/fwdpy11_arg_example/blob/benchmarks4paper/benchmarking.py) that I've written has a [flag](https://github.com/molpopgen/fwdpy11_arg_example/blob/benchmarks4paper/benchmarking.py#L31) that tells whether or not to simulate neutral variants.  If that switch is used, we run the regular fwdpy11 machinery, else we run the new machinery that generates nodes/edges for msprime in C++.

**Comment by petrelharp** [comment]
agree

On Fri, Sep 22, 2017 at 8:26 AM, Kevin R. Thornton <notifications@github.com

**Comment by ashander** [comment]
Sounds good. And for both we are just recording sim time, not e.g. time to write a whole VCF

**Comment by molpopgen** [comment]
Right. No need for output.
