### ISSUE TITLE
possibly inaccurate y-axes in RAM usage figure

### ISSUE THREAD

**Issue by ashander** [petrelharp/ftprime_ms#42]
@molpopgen are the y-axes in the right and left panes of the figure comparing RAM use without selection accurate?

(this is fig B2 in #41 but elsewhere in master; reproduced below.)

![image](https://user-images.githubusercontent.com/510776/34458818-cef0dd60-ed94-11e7-8444-72043e5351fc.png)

**Comment by molpopgen** [comment]
They're from the same files used for the timings.  What seems amiss, specifically?

**Comment by molpopgen** [comment]
I can double check the code tomorrow I any case....

**Comment by ashander** [comment]
Ah, I was thrown by `N=1e4` not being included in the simuPOP comparison. 

So I think we need to make the point more clearly (or I need to remind myself) that even though our peak RAM use with pedigree tracking in simuPOP is insanely high, it's *lower* than without tracking.

![image](https://user-images.githubusercontent.com/510776/34464102-166a03a0-ee27-11e7-9733-25b236b90053.png)
