### ISSUE TITLE
Fig 5.A: meaning of horizontal lines

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#45]
I'm confused by the horizontal line in fig 5A between nodes B and C. Since E only inherits from B, should there not just be a direct line from B to E (like we have from B to A)? 

I think we should have a quick explanation for the difference between horizontal and vertical lines. Or perhaps make one type dashed and the other full, to emphasise that they are qualitatively different?

**Comment by petrelharp** [comment]
I've made horizontal lines dotted and adjusted the caption.  What do you think?  I think that we should have the line in the pedigree between B and C, because those dotted lines mean "parents of", which is conceptually different than "contributed genome to".

**Comment by jeromekelleher** [comment]
This is good, thanks. I am still slightly confused by C being a parent of E, but not contributing any genome though... Am I just being too literal about the meaning of 'parent'?

**Comment by petrelharp** [comment]
Well, a frequent outcome of meiosis is transmission of one entire parental
chromosome.  Here, "parents" mean "the parental chromosomes that underwent
meiosis to produce the gamete".

I should really remake this figure to show diploids, though: currently it
is not a legal situation for diploids.

**Comment by petrelharp** [comment]
I have re-made these figures: the resulting tree sequence has one more tree, but now this could be the result of diploids mating (and I have said so in the caption).  I could cut out A if you think that would help?
  
The result also no longer has multiple chunks of ancestry coming together from different places into a single coalescent event at the top, which was a nice complicated bit about the previous example; but, simpler is better here.

**Comment by jeromekelleher** [comment]
Yes, I follow it now! Changing to explicitly talking about diploids makes this much easier to understand I think. This is a great figure; it really makes the forwards-time model totally clear.

Minor issues:

- "D and E were parents to F ," -> should be G?
- "(C) Simplified for I,J:" -> should read J, K

I haven't gone through the edges and trees in full detail yet, but I'll do it at some point.

**Comment by petrelharp** [comment]
whoops; yes. fixed.

**Comment by ashander** [comment]
This new fig looks great btw. Go diploids!

Also in #51 I took the time to copy/paste the tables into msprime and make it draw the trees. They agree =)
