### ISSUE TITLE
Fig 6. Clarification needed? 

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#46]
I've been staring at Fig 6 for a few minutes, and I find that I'm struggling to figure what's going on.

One thing I think might help is to show the colour being inherited to the left and right. So, for example, on the vertical line above node I, we could have a paint bar to the left and the right. On the left would be 0.9 red (like the paint bar in G), and on the right would showing 0.1 red. This would show which bits of ancestral material go to the left and to the right. This is sort-of shown already in the paint bars within the nodes, but it's confused by the effects of coalescence (node H contains the paint inherited from I and J, for example.

Also, what do the annotations (e.g.) '3rd and 4th edges' refer to?

The initial 'paint-pot' description in the text is excellent, and really captures the essence of the algorithm. Perhaps we could add another paragraph explaining the example in figure 6 in a bit more detail? We could then finish the section with a quick discussion of the time/space complexity of the algorithm by adapting the current paragraph starting with 'More concretely'.

What do you think @petrelharp?

**Comment by molpopgen** [comment]
I found this one tough, too, but I *think* I got it after staring.  I find the edge annotations confusing, too, and think that they should be labelled on the graph.

**Comment by petrelharp** [comment]
I can work on it, but first: if the text is good but the diagram is confusing, do you think we need the diagram?  

Oh! I know!  We need an SVG animation! (j/k: that'd be nice, but...)

**Comment by jeromekelleher** [comment]
> I can work on it, but first: if the text is good but the diagram is confusing, do you think we need the diagram?

I think the diagram is good, as it's probably too abstract for most people without some visual depiction of the algorithm in action. I think we just need a few slight clarifications to the diagram, but also a few sentences in the text (or caption) describing what we're looking at.

**Comment by petrelharp** [comment]
I have added something like perhaps what you mean?

**Comment by jeromekelleher** [comment]
Yep, this is much better. Thanks!
