### ISSUE TITLE
Slight terminology change: Succinct tree sequence

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#54]
Would anyone object if I changed the terminology slightly from 'tree sequence' to 'succinct tree sequence'? It's a bit vague as just a "tree sequence", which doesn't capture the fact that we're efficiently *encoding* a sequence of trees rather than it just being some sequence of trees.

I like succinct, because it has a technical meaning that is very close to what we actually do (from Wikipedia):

> In computer science, a succinct data structure is a data structure which uses an amount of space that is "close" to the information-theoretic lower bound, but (unlike other compressed representations) still allows for efficient query operations.

I don't think it's a big change, as we'll just say "A succinct tree sequence (or for brevity, a tree sequence) is ...".

**Comment by ashander** [comment]
Cool by me. Also nice to know that technical term. It's the first I'd heard of it but it's a good concept

**Comment by petrelharp** [comment]
also fine by me.  although: most people will not recognize "succinct" as a
technical term.

**Comment by molpopgen** [comment]
I'm fine with it.  It may be handy to give the compsci definition in ,, upon first use.

**Comment by petrelharp** [comment]
I'm doing it in the abstract, too...

**Comment by petrelharp** [comment]
Er, to be clear: what *is* a "tree sequence"?  Right now we *don't* really define it, other than to use it to mean "the sequence of trees", and talk about "the tables" as encoding one.  Do you mean to define "succinct tree sequence" to be the thing with `nodes` and `edges` (and `sites`, `mutations`)?  That we store in the tables, but one could store in other ways? That's what I'm going with...

**Comment by petrelharp** [comment]
In #60 I tried moving from "tree sequence format" to "succinct tree sequence".  I think we can mostly remove the word "format", referring instead to "tree sequences" or "tables" when that's what we really mean.  I'll give it a try.

**Comment by jeromekelleher** [comment]
> Er, to be clear: what is a "tree sequence"? Right now we don't really define it, other than to use it to mean "the sequence of trees", and talk about "the tables" as encoding one.

How about: "A succinct tree sequence is a tuple (N, E, S, M), where N is a set of nodes (as defined above),..." etc. The tables encode the nodes, edges etc. 

>  Do you mean to define "succinct tree sequence" to be the thing with nodes and edges (and sites, mutations)? That we store in the tables, but one could store in other ways? That's what I'm going with...

Yes, exactly.

Also good call on getting a definition of succinct in on first usage, this is an excellent idea.

**Comment by petrelharp** [comment]
The way I've got it now is not quite so precise. If you are proposing to *define* "succinct tree seq" to be the four tables, then that would let us call the tables something other than "the tables", which would be good.  I'd still want to refer to the tables, though, e.g. "we add a row to the edge table of the succinct tree sequence" rather than "we add a row to the succinct tree sequence".

However, current usage separates somewhat the idea from the particular representation in tables, which is conceptually nice.
